services:
#    data_dictionary_object_bridge.example:
#        class: Youwe\DataDictionaryObjectBridgeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    datadictionary.builder:
        class: Youwe\DataDictionaryObjectBridgeBundle\Builder
        public: true
        autowiring: true
        autoconfigure: true
        tags: ['datadictionary']
